### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Useless-Panda** [NerdSmith/MusicRecognizer#2]
Hi! it's not working for me

INFO:root:devices have been found
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443
DEBUG:urllib3.connectionpool:https://nameless-sierra-10297.herokuapp.com:443 "GET / HTTP/1.1" 200 14
ERROR:root:record error [Errno -9996] Invalid device

**Comment by NerdSmith** [comment]
> Hi! it's not working for me
> 
> INFO:root:devices have been found DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): nameless-sierra-10297.herokuapp.com:443 DEBUG:urllib3.connectionpool:https://nameless-sierra-10297.herokuapp.com:443 "GET / HTTP/1.1" 200 14 ERROR:root:record error [Errno -9996] Invalid device

Hello, can you tell me what version of Windows are you using? And what device do you choose from the menu?
It will be great if you specify the detailed characteristics of your device.

**Comment by Useless-Panda** [comment]
I am using Win 7 and input device is Speaker (High Definition Audio device)

**Comment by NerdSmith** [comment]
> I am using Win 7 and input device is Speaker (High Definition Audio device)

Try connecting speakers or headphones via a 3.5 or USB connector and select listening through them in the [system sounds](https://answers.microsoft.com/en-us/windows/forum/all/how-to-change-default-audio-output/19e0bcb7-a5e5-4960-b7b8-284f9d573e2b). Then actually select this device in the application menu.
By the way, be sure to update your audio drivers.
I also advise you to upgrade to Windows 10, because the problem may be precisely because of the old version of Windows (the application was only tested on Windows 10)
In the next versions of the application (version 1.0 I think to release in mid-August, after my work projects) I will make more complete information about errors in the logs so that I can specifically track down what caused the error.

**Comment by Useless-Panda** [comment]
i have connected my headphones via 3.5 connector and also selected it as default playback device. you might want to take a look at this [WhatAmIHearing](https://github.com/zemoto/WhatAmIHearing) as this program is working

**Comment by NerdSmith** [comment]
> i have connected my headphones via 3.5 connector and also selected it as default playback device. you might want to take a look at this [WhatAmIHearing](https://github.com/zemoto/WhatAmIHearing) as this program is working

It's strange that 3.5 headphones are recognized as an HDA device...
Anyway, thanks for the link, but this application uses a C# library to record sound. Maybe I should think about using Cpp library for sound recording...

**Comment by Useless-Panda** [comment]
Okay, Thanks
